W7/D2/jukebox/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only:[:new, :create, :show]

  resource :session, only:[:new, :create, :destroy]

  resources :artists
  
  resources :albums, only: [:create, :edit, :show, :update, :destroy]

  resources :artists do
    resources :albums, only: :new
  end
end

W7/D2/jukebox/app/models/album.rb
class Album < ApplicationRecord
    validates :title, presence: true
    validates :year, presence: true

    belongs_to :artist,
    foreign_key: :album_id,
    class_name: :Artist
end

W7/D2/jukebox/app/models/artist.rb
class Artist < ApplicationRecord

    validates :name, presence:true

    has_many :albums,
    foreign_key: :artist_id,
    class_name: :Album
    
end

W7/D2/jukebox/app/models/user.rb
class User < ApplicationRecord

    validates :password_digest, presence: {message: "The password cannot be blank"}
    validates :session_token, presence: true, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}

    before_validation :ensure_session_token

    attr_reader :password

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil unless user && user.is_password?(password)
        user
    end

    def is_password?(password)
        bcrypt = BCrypt::Password.new(self.password_digest)
        bcrypt.is_password?(password)
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    private

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end
end

W7/D2/jukebox/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def create
        @album = Album.new(album_params)
        if @album.save
            
        else
        end
    end
end

W7/D2/jukebox/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def login!(user)
        session[:session_token] = user.reset_session_token!
        @current_user = user
    end

    def logout!
        current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
    end

    def current_user
        @current_user ||= User.find_by( session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def ensure_logged_in
        redirect_to new_session_url unless logged_in?
    end
end

W7/D2/jukebox/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    def index
        @artists = Artist.all
        render :index
    end

    def new
        @artist = Artist.new
        render :new
    end

    def create
        @artist = Artist.new(artist_params)
        if @artist.save
            redirect_to artist_url(@artist.id)
        else
            flash.now[:errors] = ["This is an invalid artist name."]
            render :new
        end
    end

    def edit
        @artist = Artist.find(params[:id])
        render :edit
    end

    def update
        @artist = Artist.find(params[:id])
        if @artist.update(artist_params)
            redirect_to artist_url(@artist.id)
        else
            flash.now[:errors] = ["This is an invalid update."]
            render :edit
        end
    end

    def show
        @artist = Artist.find(params[:id])
        render :show
    end

    def destroy
        @artist = Artist.find(params[:id])
        @artist.destroy
        redirect_to artists_url
    end

    private 

    def artist_params
        params.require(:artist).permit(:name)
    end
end

W7/D2/jukebox/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new
    end
    
    def create
        user = User.find_by_credentials(
            params[:user][:email],
            params[:user][:password]
        )

        if user
            login!(user)
            redirect_to user_url(user.id)
            # redirect to songs
        else
            flash.now[:errors] = ["This is not a valid user"]
            render :new, status: 422
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

W7/D2/jukebox/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user.id)
            # redirect_to songs
        else
            flash.now[:errors] = @users.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

W7/D2/jukebox/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jukebox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if logged_in?%>
      <form action="<%= session_url%>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
        <input type="submit" value="Logout">
      </form>
    <%else%>
      <header> 
        <a href="<%= new_session_url %>">Log In!</a>
        <a href="<%= new_user_url%>">Sign Up!</a>
      </header>
    <%end%>

    <h1>Ooi's Jukebox</h1>

    <%if flash.now[:errors]%>
      <ul>
        <% flash.now[:errors].each do |error| %>
          <li><%= error%></li>
        <%end%>
      </ul>
    <%end%>

    <%= yield %>
  </body>
</html>

W7/D2/jukebox/app/views/users/new.html.erb
<form action="<%= users_url %>" method="POST">

    <h1>Create a new User</h1>

    <input type="hidden" name="authenticity_token" value = "<%= form_authenticity_token %>">
    
    <label for="email">Email</label>
    <input id="email" type="text" name="user[email]" value="<%= @user.email %>">

    <label for="password">Password</label>
    <input id="password" type="password" name="user[password]" value="<%= @user.password %>">

    <input type="submit" value="Sign Up!">

</form>

W7/D2/jukebox/app/views/users/show.html.erb
<h1><%=@user.email%></h1>