W8/reddit-clone/config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user GET    /users/:id(.:format)                                                                     users#show
#               new_session GET    /session/new(.:format)                                                                   sessions#new
#                   session DELETE /session(.:format)                                                                       sessions#destroy
#                           POST   /session(.:format)                                                                       sessions#create
#                      subs GET    /subs(.:format)                                                                          subs#index
#                           POST   /subs(.:format)                                                                          subs#create
#                   new_sub GET    /subs/new(.:format)                                                                      subs#new
#                  edit_sub GET    /subs/:id/edit(.:format)                                                                 subs#edit
#                       sub GET    /subs/:id(.:format)                                                                      subs#show
#                           PATCH  /subs/:id(.:format)                                                                      subs#update
#                           PUT    /subs/:id(.:format)                                                                      subs#update
#                           DELETE /subs/:id(.:format)                                                                      subs#destroy
#                     posts POST   /posts(.:format)                                                                         posts#create
#                  new_post GET    /posts/new(.:format)                                                                     posts#new
#                 edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                      post GET    /posts/:id(.:format)                                                                     posts#show
#                           PATCH  /posts/:id(.:format)                                                                     posts#update
#                           PUT    /posts/:id(.:format)                                                                     posts#update
#                           DELETE /posts/:id(.:format)                                                                     posts#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :index, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :subs

  resources :posts, only:[:new, :create, :show, :edit, :update, :destroy]
  
end

W8/reddit-clone/app/models/post.rb
class Post < ApplicationRecord

    has_many :sub_posts,
    foreign_key: :post_id,
    class_name: :SubPost,
    inverse_of: :post

    has_many :subs,
    through: :sub_posts,
    source: :sub

end

W8/reddit-clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :is_author?, only:[:edit, :update]
    before_action :require_login!, only:[:new, :create]

    def show
        @post = Post.find(params[:id])
        render :show
    end

    def new
        @post = Post.new
        render :new
    end


    #1,2,3
    def create
        @post = Post.new(post_params)
        @post.author_id = current_user.id
        @post.sub_ids = [1,2]
        debugger
        if @post.save
            redirect_to post_url(@post.id)
        else
            flash.now[:errors] = ["Not a valid post"]
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
        render :edit
    end

    def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            redirect_to(post_url(@post.id))
        else
            flash.now[:errors] = ["This is an invalid update to post"]
            render :edit
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to sub_url(@post.sub_id)
    end

    private

    def post_params
        params.require(:post).permit(:title, :url, :content)
    end
end

W8/reddit-clone/app/views/posts/edit.html.erb
<h1>Edit a Post</h1>

<form action="<%= posts_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
    <input type="hidden" name="_method" value="patch">

    <label>Title<input type="text" name="post[title]" value="<%= @post.title %>"/>
    <br>
    <br>
    <label>Url<input type="text" name="post[url]" value="<%= @post.url %>"/>
    <br>
    <br>
    <label for="content">Enter Content</label>
    <br>
    <textarea id="content" name="post[content]"><%= @post.content %></textarea>
    <br>
    <br>
    <br>

    <h3>Post to:</h3>
    <input type="hidden" name="post[sub_ids][]" value="">
    <%Sub.all.each do |sub|%>
        <br>
        <label for="<%=sub.title%>"><%=sub.title%></label>
        <input id="<%=sub.title%>" type="checkbox" name="post[sub_ids][]" value="<%=sub.id%>" <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    <%end%>
    <br>
    <br>
    <button type="submit">Create Post</button>
</form>

W8/reddit-clone/app/views/posts/new.html.erb
<h1>Create a Post</h1>

<form action="<%= posts_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>

    <label>Title<input type="text" name="post[title]" value="<%= @post.title %>"/>
    <br>
    <br>
    <label>Url<input type="text" name="post[url]" value="<%= @post.url %>"/>
    <br>
    <br>
    <label for="content">Enter Content</label>
    <br>
    <textarea id="content" name="post[content]"><%= @post.content %></textarea>
    <br>
    <br>
    <br>

    <h3>Post to:</h3>
    <%Sub.all.each do |sub|%>
        <br>
        <label for="<%=sub.title%>"><%=sub.title%></label>
        <input id="<%=sub.title%>" type="checkbox" name="post[sub_ids][]" value="<%=sub.id%>">
    <%end%>
    <br>
    <br>
    <button type="submit">Create Post</button>
</form>

W8/reddit-clone/app/views/posts/show.html.erb
<h1><%=@post.title%></h1>

<br>
<br>
<br>

<%if @post.url%>
    <a href="<%=@post.url%>">Link</a>
<%end%>

<br>
<br>
<br>


<%if @post.content%>
    <p><%=@post.content%></p>
<%end%>